### ISSUE TITLE
workerが動かない

### ISSUE THREAD

**Issue by kyonsuke** [ppworks/mentions#69]
うまくメンションがslackに通知されなかったので、ソースコードを見て
webhockの通知時にjobをperform_laterで呼んでる箇所を見かけたので
workerを立ち上げてみたところ、設定が無いので動きませんでした

```
Don't know how to build task 'jobs:work' (see --tasks)
2017-03-07T06:47:32.427687+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
2017-03-07T06:47:32.427688+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
2017-03-07T06:47:32.427689+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
2017-03-07T06:47:32.427689+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
2017-03-07T06:47:32.427690+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
2017-03-07T06:47:32.427691+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2017-03-07T06:47:32.427692+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2017-03-07T06:47:32.427693+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
2017-03-07T06:47:32.427693+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
2017-03-07T06:47:32.427694+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
2017-03-07T06:47:32.427694+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
2017-03-07T06:47:32.427695+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
2017-03-07T06:47:32.427696+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
2017-03-07T06:47:32.427696+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
2017-03-07T06:47:32.427697+00:00 app[worker.1]: /app/bin/bundle:3:in `load'
2017-03-07T06:47:32.427698+00:00 app[worker.1]: /app/bin/bundle:3:in `<main>'
2017-03-07T06:47:32.427701+00:00 app[worker.1]: (See full trace by running task with --trace)
```

どのようにすれば良いでしょうか？

**Comment by ppworks** [comment]
> perform_later


:eyes: http://edgeguides.rubyonrails.org/active_job_basics.html#the-purpose-of-active-job

> Rails by default comes with an asynchronous queuing implementation that runs jobs with an in-process thread pool. Jobs will run asynchronously, but any jobs in the queue will be dropped upon restart.

If you want to use a queuing backend, please fork this repository and set up [queuing backend](http://edgeguides.rubyonrails.org/active_job_basics.html#setting-the-backend).
